[env:esp32-s3-devkitc-1]
platform = platformio/espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_qspi
lib_extra_dirs = D:/Documents/Arduino/libraries
;upload_protocol = esptool
;upload_protocol = esp-builtin
; (thay bằng cổng của bạn)

monitor_port = COM12



build_flags =
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-D USER_SETUP_LOADED=1
	-D GC9A01_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	-D TFT_MISO=-1
	-D TFT_SCLK=13
	-D TFT_MOSI=12
	-D TFT_DC=11
	-D TFT_CS=10
	-D TFT_RST=9                               
	-D TFT_BL=14
	-D TFT_BACKLIGHT_ON=HIGH
	-D CORE_DEBUG_LEVEL=3
	-D USE_HSPI_PORT=1
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=20000000
	-D CONFIG_ESP_BROWNOUT_DET=0
	-D CONFIG_ESP32S3_BROWNOUT_DET=0

lib_deps =
	bodmer/TFT_eSPI @ ^2.5.43
	h2zero/NimBLE-Arduino @ ^1.4.1
	bitbank2/JPEGDEC @ ^1.5.0
	fbiego/ESP32Time @ ^2.0.4
	mathertel/OneButton @ ^2.5.0
	bblanchon/ArduinoJson @ ^7.0.4
	FontMaker


