[env:esp32-s3-devkitc-1]
platform = platformio/espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_RUNNING_CORE=1
	-D ARDUINO_EVENT_RUNNING_CORE=1
	-D USER_SETUP_LOADED=1
	-D GC9A01_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	-D TFT_MISO=-1
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TFT_CS=13
	-D TFT_DC=9
	-D TFT_RST=10
	-D SPI_FREQUENCY=40000000
	-D USE_HSPI_PORT=1
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1

lib_deps = 
	bodmer/TFT_eSPI @ ^2.5.43 