[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_upload.flash_size = 4MB

lib_deps =
    olikraus/U8g2 @ ^2.35.19
    h2zero/NimBLE-Arduino @ ^1.4.1
    mathertel/OneButton @ ^2.5.0
    fbiego/ESP32Time @ ^2.0.6

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DOLED_SDA=6
    -DOLED_SCL=7
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL=1
